name: reusable one
on:
  workflow_call:
    outputs:
      runId:
        description: "The run-id of the workflow"
        value: $${{ github.run_id }}

jobs:
 upload:
   runs-on: ubuntu-latest
   steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: readme
        path: README.md
