name: Call other workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/one.yml
    secrets: inherit
  read:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: print id
        env:
          ID: ${{ github.run_id }}
        run: |
          echo $ID
      - name: Download  artifact
        uses: actions/download-artifact@v4
        with:
          name: readme
          path: README2.md
          run-id: ${{ needs.build.outputs.runId }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  
